AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName:
    Description: Domain name of recordostyle
    Type: String

Resources:
  RecordostyleHostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: !Sub ${DomainName}.
      HostedZoneConfig:
          Comment: Public DNS zone of recordostyle

  RecordostyleRecordSetGroup:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref RecordostyleHostedZone
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: 
              Fn::ImportValue: recordostyle-cloudfront-domain
