AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName:
    Description: Domain name of recordostyle
    Type: String

Resources:
  RecordostyleHostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: !Sub ${DomainName}.
      HostedZoneConfig:
          Comment: Public DNS zone of recordostyle

Outputs:
  RecordostyleHostedZoneId:
    Description: "Recordostyle HostedZone ID"
    Value:
      !Ref RecordostyleHostedZone
    Export:
      Name: recordostyle-hostedzone-id
