name: Deploy to Amazon S3

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy S3 Bucket
    runs-on: ubuntu-latest
    environment: PROD
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
        aws-region: us-east-2

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: s3-bucket-stack
        template: s3-bucket.yml
        parameter-overrides: ""