name: Deploy Recordostyle's infra

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: "Deploy Infra of Recordostyle"
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::118186523911:role/recordostyle-github-assume-role
        aws-region: us-east-1

    - name: Deploy recordostyle's public Hostedzone
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: recordostyle-hostedzone
        template: hostedzone.yml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: "DomainName=recordostyle.com"

    - name: Deploy recordostyle's main infra
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: recordostyle-main-infra
        template: main-infra.yml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: "DomainName=recordostyle.com,CachePolicy=CachingDisabled" # TODO: change to CachingOptimized once it go live


