name: Deploy to Amazon S3

on:
  push:
    branches: [ "main" ]

env:
  DOMAIN_NAME: recordostyle.com

jobs:
  deploy:
    name: "Deploy S3 Bucket, Cloudfront Distrubution & Route53"
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::118186523911:role/recordostyle-github-assume-role
        aws-region: us-east-2

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: s3-cloudfront
        template: s3-cloudfront.yml
        parameter-overrides: "DomainName=$DOMAIN_NAME,CachePolicy=CachingDisabled" # TODO: change to CachingOptimized once it go live

    - name: Deploy to AWS Route53
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: s3-cloudfront
        template: route53.yml
        parameter-overrides: "DomainName=$DOMAIN_NAME"

